
-- =============================================================================
-- Project: Battery Pack & Module Manufacturing Execution System (CellMES)
-- File:    schema_definition.sql
-- Dialect: PostgreSQL 13+
-- Author:  Engineering Team
-- =============================================================================
-- PURPOSE:
--   This Data Definition Language (DDL) script provisions the complete schema 
--   for the Battery Pack & Module Manufacturing Execution System (MES). It 
--   manages end-to-end traceability, shop-floor execution, inspection records,
--   and master configurations for electric vehicle (EV) battery production.
--
-- ARCHITECTURAL OVERVIEW:
--   1. Master Configurations:
--      Manages baseline specifications for cell chemistries, module/BMS 
--      variants, pack configurations, user authorizations, and defect taxonomies.
--
--   2. Work Order Execution:
--      Maintains operational lifecycles (SCHEDULED, STARTED, REWORKED, HOLD, 
--      COMPLETED) for both module sub-assemblies (`cellmess_app_module_wo`) and 
--      final battery pack integrations (`cellmes_app_pack_wo`), including Kafka 
--      stream synchronization markers.
--
--   3. Component Traceability & Assembly (Genealogy):
--      Captures 1-to-1 and 1-to-many physical marriages between battery packs, 
--      BMS identifiers, Left-Hand (LH) modules, and Right-Hand (RH) modules 
--      across standard MES flows (`cellmes_app_lhrl_scan`) and external/manual 
--      lines (`cellmes_app_lhrh_scan_nonmes`).
--
--   4. Station Quality Gates & Serialization:
--      Maintains cycle metrics, raw parameter logs, and pass/fail states for:
--        - Pressure Drop Leak Testing (`cellmes_app_leaktest`)
--        - Pre-End of Line (Pre-EOL) High-Voltage Verification (`cellmes_app_pre_eol`)
--        - End-of-Line / Chroma Electrical & Thermal Characterization (`cellmes_app_eol`)
--        - Pre-Delivery Inspection / Final Quality Gate (`cellmes_pdi_station`)
--        - Non-Conformance & Rework Clearance Workflow (`cellmes_app_nc_clearance`)
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. EXTENSIONS & CUSTOM DOMAIN TYPES (ENUMS)
-- =============================================================================

DO $$ BEGIN
    CREATE TYPE public.final_result AS ENUM ('PASS', 'FAIL');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE public.cell_type AS ENUM ('BAK', 'LG', 'OLA');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE public.wo_status AS ENUM ('SCHEDULED', 'STARTED', 'REWORKED', 'HOLD', 'COMPLETED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE public.active_status_battery AS ENUM ('ACTIVE', 'INACTIVE');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE public.nc_station_id AS ENUM ('LEAK_TEST', 'PRE_EOL', 'EOL', 'PDI');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;


-- =============================================================================
-- 2. USER ACCESS CONTROL & MASTER CONFIGURATION TABLES
-- =============================================================================

-- RBAC Group Master
CREATE TABLE IF NOT EXISTS public.cellmes_master_usergroup
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    group_name     VARCHAR(50) NOT NULL,
    is_active      VARCHAR(10) NOT NULL DEFAULT 'YES',
    created_date   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updation_time  TIMESTAMPTZ,
    CONSTRAINT cellmes_master_usergroup_pkey PRIMARY KEY (id)
);

-- User Credentials and Profile Register
CREATE TABLE IF NOT EXISTS public.cellmes_master_users
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_group         INTEGER NOT NULL,
    user_name          VARCHAR(50) NOT NULL,
    user_id            VARCHAR(50) NOT NULL,
    email              VARCHAR(50),
    failed_attempt     INTEGER NOT NULL DEFAULT 0,
    last_login_attemt  TIMESTAMPTZ,
    is_active          VARCHAR(10) NOT NULL DEFAULT 'YES',
    password_hash      VARCHAR(255) NOT NULL,
    CONSTRAINT cellmes_master_users_pkey PRIMARY KEY (id),
    CONSTRAINT cellmes_master_users_user_id_key UNIQUE (user_id)
);

-- Cell Classification and Power Profile Master
CREATE TABLE IF NOT EXISTS public.cellmes_master_celltype_config
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    kw             VARCHAR(10) NOT NULL,
    celltype       VARCHAR(10) NOT NULL,
    is_active      VARCHAR(10) NOT NULL DEFAULT 'YES',
    creation_time  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updation_time  TIMESTAMPTZ,
    CONSTRAINT cellmes_master_celltype_config_pkey PRIMARY KEY (id)
);

-- Module Master Catalog
CREATE TABLE IF NOT EXISTS public.cellmes_master_module_master
(
    id            SERIAL,
    model         VARCHAR(50),
    part_no       VARCHAR(16),
    lh_part_no    VARCHAR(16),
    rh_part_no    VARCHAR(16),
    part_name     VARCHAR(10),
    kw            VARCHAR(5),
    created_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT cellmes_master_module_master_pkey PRIMARY KEY (id)
);

-- Module Material Specification Master
CREATE TABLE IF NOT EXISTS public.cellmes_master_module_config
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    module_name         VARCHAR(50),
    module_material_id  VARCHAR(20) NOT NULL,
    is_active           VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    creation_date       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updation_date       TIMESTAMPTZ,
    CONSTRAINT cellmes_master_module_config_pkey PRIMARY KEY (id)
);

-- Battery Management System (BMS) Hardware Master
CREATE TABLE IF NOT EXISTS public.cellmes_master_bms_config
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    bms_name         VARCHAR(50),
    bms_material_id  VARCHAR(14) NOT NULL,
    is_active        VARCHAR(10) NOT NULL DEFAULT 'YES',
    created_date     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date     TIMESTAMPTZ,
    CONSTRAINT cellmes_master_bms_config_pkey PRIMARY KEY (id)
);

-- Battery Pack SKU & Part Configuration
CREATE TABLE IF NOT EXISTS public.cellmes_master_pack_config
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    pack_name         VARCHAR(50),
    pack_material_id  VARCHAR(14) NOT NULL,
    is_active         VARCHAR(10) NOT NULL DEFAULT 'YES',
    created_date      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date      TIMESTAMPTZ,
    CONSTRAINT cellmes_master_pack_config_pkey PRIMARY KEY (id)
);

-- Top-level Battery Bill of Materials (BOM) Relationship Register
CREATE TABLE IF NOT EXISTS public.cellmes_master_battery_config
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    pack_id       INTEGER NOT NULL,
    bms_id        INTEGER NOT NULL,
    module_id     INTEGER NOT NULL,
    is_active     public.active_status_battery NOT NULL DEFAULT 'ACTIVE',
    created_date  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_      TIMESTAMPTZ,
    CONSTRAINT cellmes_master_battery_config_pkey PRIMARY KEY (id)
);

-- Status Lookups & Defect Categorizations
CREATE TABLE IF NOT EXISTS public.cellmes_master_battery_status
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    status_name  VARCHAR(50),
    is_active    VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT cellmes_master_battery_status_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cellmes_master_defect_list
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    defect_name  VARCHAR(50),
    is_active    VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT cellmes_master_defect_list_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cellmes_master_defect_source
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    defect_name  VARCHAR(50),
    is_active    VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT cellmes_master_defect_source_pkey PRIMARY KEY (id)
);


-- =============================================================================
-- 3. PRODUCTION PLANNING & WORK ORDER EXECUTION TABLES
-- =============================================================================

-- Module Assembly Production Orders
CREATE TABLE IF NOT EXISTS public.cellmess_app_module_wo
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    wo_number        VARCHAR(24) NOT NULL,
    po_number        VARCHAR(24) NOT NULL,
    material_number  VARCHAR(24) NOT NULL,
    part_name        VARCHAR(80) NOT NULL,
    bop_id           VARCHAR(10) NOT NULL,
    work_station     VARCHAR(16) NOT NULL,
    status           VARCHAR(50) NOT NULL,
    schedule_time    TIMESTAMP WITHOUT TIME ZONE,
    job_end_time     TIMESTAMPTZ,
    created_on       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on       TIMESTAMPTZ,
    wo_used          INTEGER NOT NULL DEFAULT 0,
    line_id          INTEGER,
    CONSTRAINT cellmess_app_module_wo_pkey PRIMARY KEY (id),
    CONSTRAINT cellmess_app_module_wo_number_key UNIQUE (wo_number)
);

-- Pack Assembly Production Orders
CREATE TABLE IF NOT EXISTS public.cellmes_app_pack_wo
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    wo_number            VARCHAR(24) NOT NULL,
    po_number            VARCHAR(24) NOT NULL,
    schedule_time        TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    start_time           TIMESTAMPTZ,
    end_time             TIMESTAMPTZ,
    wo_status            public.wo_status NOT NULL,
    work_station         VARCHAR(16),
    created_on           TIMESTAMPTZ,
    order_type           VARCHAR(16),
    material_number      VARCHAR(24),
    bop_id               VARCHAR(24),
    part_name            VARCHAR(80),
    wo_used              INTEGER NOT NULL DEFAULT 0,
    is_sendto_kafka      INTEGER DEFAULT 0,
    kafka_start_time     TIMESTAMPTZ,
    is_sendto_kafka_end  INTEGER DEFAULT 0,
    kafka_end_time       TIMESTAMPTZ,
    CONSTRAINT cellmes_app_pack_wo_pkey PRIMARY KEY (id),
    CONSTRAINT cellmes_app_pack_wo_wo_number_key UNIQUE (wo_number)
);


-- =============================================================================
-- 4. SERIALIZATION, TRACEABILITY & SUB-ASSEMBLY SCANS
-- =============================================================================

-- Left-Hand (LH) / Right-Hand (RH) Module Inline Scanning (MES Flow)
CREATE TABLE IF NOT EXISTS public.cellmes_app_lhrl_scan
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    wo_id            BIGINT NOT NULL,
    lh_serial        VARCHAR(12) NOT NULL,
    lh_cell_type     public.cell_type,
    lh_kw            VARCHAR(10),
    is_lh_consumed   INTEGER NOT NULL DEFAULT 0,
    rh_serial        VARCHAR(12) NOT NULL,
    rh_cell_type     public.cell_type,
    rh_kw            VARCHAR(10),
    is_rh_consumed   INTEGER NOT NULL DEFAULT 0,
    module_serial    VARCHAR(12) NOT NULL,
    created_date     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date     TIMESTAMPTZ,
    line_id          INTEGER,
    material_number  VARCHAR(24),
    CONSTRAINT cellmes_app_lhrl_scan_pkey PRIMARY KEY (id)
);

-- External / Legacy Line Module Traceability
CREATE TABLE IF NOT EXISTS public.cellmes_app_lhrh_scan_nonmes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    lh_serial      VARCHAR(20) NOT NULL,
    lh_celltype    public.cell_type,
    lh_kw          VARCHAR(10),
    rh_serial      VARCHAR(20) NOT NULL,
    rh_celltype    public.cell_type,
    rh_kw          VARCHAR(10),
    module_serial  VARCHAR(20),
    creation_date  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updation_date  TIMESTAMPTZ,
    CONSTRAINT cellmes_app_lhrh_scan_nonmes_pkey PRIMARY KEY (id)
);

-- Central Battery Pack Marriage Register
CREATE TABLE IF NOT EXISTS public.cellmes_app_pack_scan
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    wo_id           BIGINT NOT NULL,
    pack_number     VARCHAR(52) NOT NULL,
    lh_id           BIGINT,
    rh_id           BIGINT,
    bms_number      VARCHAR(74) NOT NULL,
    pre_eol_status  VARCHAR(10) NOT NULL DEFAULT 'NO',
    chroma_status   VARCHAR(10) NOT NULL DEFAULT 'NO',
    pdi_status      VARCHAR(10) NOT NULL DEFAULT 'NO',
    overall_status  VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    created_date    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date    TIMESTAMPTZ,
    lhrh_id_nonmes  BIGINT,
    CONSTRAINT cellmes_app_pack_scan_pkey PRIMARY KEY (id),
    CONSTRAINT cellmes_app_pack_scan_pack_number_key UNIQUE (pack_number)
);


-- =============================================================================
-- 5. QUALITY TESTING & INSPECTION GATE LEDGERS
-- =============================================================================

-- Station 1: Pressure Decay Leak Testing
CREATE TABLE IF NOT EXISTS public.cellmes_app_leaktest
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    pack_id           BIGINT NOT NULL,
    leak_test_value   INTEGER,
    leak_test_result  public.final_result,
    is_reworked       INTEGER NOT NULL DEFAULT 0,
    test_start_time   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date      TIMESTAMPTZ,
    CONSTRAINT cellmes_app_leaktest_pkey PRIMARY KEY (id)
);

-- Station 2: Pre-End of Line (Pre-EOL) High Voltage Verification
CREATE TABLE IF NOT EXISTS public.cellmes_app_pre_eol
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    pack_id         BIGINT NOT NULL,
    pre_eol_status  public.final_result NOT NULL,
    category        VARCHAR(50),
    remarks         VARCHAR(50),
    is_reworked     INTEGER NOT NULL DEFAULT 0,
    created_date    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date    TIMESTAMPTZ,
    CONSTRAINT cellmes_app_pre_eol_pkey PRIMARY KEY (id)
);

-- Station 3: End of Line (EOL) / Chroma Cycler Testing
CREATE TABLE IF NOT EXISTS public.cellmes_app_eol
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    pack_id                   BIGINT NOT NULL,
    inspectiondate            TIMESTAMPTZ,
    tester_id                 VARCHAR(10),
    channel_id                INTEGER,
    cell_deviation            VARCHAR(10),
    cell_minimum              VARCHAR(10),
    temperature_diff_pdu      VARCHAR(10),
    final_pack_voltage        VARCHAR(10),
    final_soc                 VARCHAR(10),
    bms_dcdc_voltage          VARCHAR(10),
    cell_maximum              VARCHAR(10),
    start_soc                 VARCHAR(10),
    battery_pack_temperature  VARCHAR(10),
    minimumdischargevoltage   VARCHAR(10),
    dc_dc                     VARCHAR(10),
    cycle_count               VARCHAR(10),
    battery_pack_temp         VARCHAR(10),
    cell_voltage              VARCHAR(10),
    temperature_difference    VARCHAR(10),
    total_voltage             VARCHAR(10),
    pdu_temp_difference       VARCHAR(10),
    soc_states                VARCHAR(10),
    cell_voltage_deviation    VARCHAR(10),
    final_status              public.final_result,
    start_time                VARCHAR(20),
    end_time                  VARCHAR(20),
    creation_date             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updation_date             TIMESTAMP WITHOUT TIME ZONE,
    is_reworked               INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT cellmes_app_eol_pkey PRIMARY KEY (id)
);

-- Station 4: Pre-Delivery Inspection (PDI) / Final Mechanical Gate
CREATE TABLE IF NOT EXISTS public.cellmes_pdi_station
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    pack_id           BIGINT NOT NULL,
    leak_test_status  VARCHAR(10) NOT NULL,
    pre_eol_status    VARCHAR(10) NOT NULL,
    chroma_test       VARCHAR(255) NOT NULL,
    "PDI"             VARCHAR(50),
    defect_name       VARCHAR(50),
    pdi_remarks       VARCHAR(50),
    pack_status       VARCHAR(50),
    defect_source     VARCHAR(50),
    rework_count      INTEGER,
    is_reworked       INTEGER NOT NULL DEFAULT 0,
    created_date      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date       TIMESTAMPTZ,
    CONSTRAINT cellmes_pdi_station_pkey PRIMARY KEY (id)
);

-- Quality Rework & Non-Conformance Clearance Routing
CREATE TABLE IF NOT EXISTS public.cellmes_app_nc_clearance
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    pack_id          BIGINT NOT NULL,
    pack_serial      VARCHAR(60),
    station_id       public.nc_station_id NOT NULL,
    nc_cleared       VARCHAR(10) NOT NULL DEFAULT 'NO',
    fail_reason      VARCHAR(50),
    remarks          VARCHAR(150),
    created_date     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date     TIMESTAMPTZ,
    nc_cleared_date  TIMESTAMPTZ,
    CONSTRAINT cellmes_app_nc_clearance_pkey PRIMARY KEY (id)
);


-- =============================================================================
-- 6. FOREIGN KEY CONSTRAINT DECLARATIONS
-- =============================================================================

-- Master Relationships
ALTER TABLE public.cellmes_master_users
    ADD CONSTRAINT cellmes_master_users_user_group_fkey FOREIGN KEY (user_group)
    REFERENCES public.cellmes_master_usergroup (id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE public.cellmes_master_battery_config
    ADD CONSTRAINT cellmes_master_battery_config_bms_id_fkey FOREIGN KEY (bms_id)
    REFERENCES public.cellmes_master_bms_config (id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE public.cellmes_master_battery_config
    ADD CONSTRAINT cellmes_master_battery_config_module_id_fkey FOREIGN KEY (module_id)
    REFERENCES public.cellmes_master_module_config (id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE public.cellmes_master_battery_config
    ADD CONSTRAINT cellmes_master_battery_config_pack_id_fkey FOREIGN KEY (pack_id)
    REFERENCES public.cellmes_master_pack_config (id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

-- Execution & Module Scanning Relationships
ALTER TABLE public.cellmes_app_lhrl_scan
    ADD CONSTRAINT cellmes_app_lhrl_scan_wo_id_fkey FOREIGN KEY (wo_id)
    REFERENCES public.cellmess_app_module_wo (id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

-- Pack Scan Parentage Relationships
ALTER TABLE public.cellmes_app_pack_scan
    ADD CONSTRAINT cellmes_app_pack_scan_wo_id_fkey FOREIGN KEY (wo_id)
    REFERENCES public.cellmes_app_pack_wo (id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE public.cellmes_app_pack_scan
    ADD CONSTRAINT cellmes_app_pack_scan_lh_id_fkey FOREIGN KEY (lh_id)
    REFERENCES public.cellmes_app_lhrl_scan (id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.cellmes_app_pack_scan
    ADD CONSTRAINT cellmes_app_pack_scan_rh_id_fkey FOREIGN KEY (rh_id)
    REFERENCES public.cellmes_app_lhrl_scan (id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.cellmes_app_pack_scan
    ADD CONSTRAINT cellmes_app_pack_scan_lhrh_id_nonmes_fkey FOREIGN KEY (lhrh_id_nonmes)
    REFERENCES public.cellmes_app_lhrh_scan_nonmes (id)
    ON UPDATE CASCADE ON DELETE SET NULL;

-- Quality Stations Pack Parent Linkages
ALTER TABLE public.cellmes_app_leaktest
    ADD CONSTRAINT cellmes_app_leaktest_pack_id_fkey FOREIGN KEY (pack_id)
    REFERENCES public.cellmes_app_pack_scan (id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.cellmes_app_pre_eol
    ADD CONSTRAINT cellmes_app_pre_eol_pack_id_fkey FOREIGN KEY (pack_id)
    REFERENCES public.cellmes_app_pack_scan (id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.cellmes_app_eol
    ADD CONSTRAINT cellmes_app_eol_pack_id_fkey FOREIGN KEY (pack_id)
    REFERENCES public.cellmes_app_pack_scan (id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.cellmes_pdi_station
    ADD CONSTRAINT cellmes_pdi_station_pack_id_fkey FOREIGN KEY (pack_id)
    REFERENCES public.cellmes_app_pack_scan (id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.cellmes_app_nc_clearance
    ADD CONSTRAINT cellmes_app_nc_clearance_pack_id_fkey FOREIGN KEY (pack_id)
    REFERENCES public.cellmes_app_pack_scan (id)
    ON UPDATE CASCADE ON DELETE CASCADE;


-- =============================================================================
-- 7. PERFORMANCE & INDEXING ARCHITECTURE
-- =============================================================================

-- Master & Work Order Fast Lookups
CREATE INDEX IF NOT EXISTS idx_users_user_group 
    ON public.cellmes_master_users (user_group);

CREATE INDEX IF NOT EXISTS idx_lhrl_scan_wo_id 
    ON public.cellmes_app_lhrl_scan (wo_id);

CREATE INDEX IF NOT EXISTS idx_pack_wo_status 
    ON public.cellmes_app_pack_wo (wo_status);

CREATE INDEX IF NOT EXISTS idx_pack_wo_created_on 
    ON public.cellmes_app_pack_wo (created_on);

-- Central Pack Assembly Lookups
CREATE INDEX IF NOT EXISTS idx_pack_scan_wo_id 
    ON public.cellmes_app_pack_scan (wo_id);

CREATE INDEX IF NOT EXISTS idx_pack_scan_lh_id 
    ON public.cellmes_app_pack_scan (lh_id);

CREATE INDEX IF NOT EXISTS idx_pack_scan_rh_id 
    ON public.cellmes_app_pack_scan (rh_id);

CREATE INDEX IF NOT EXISTS idx_pack_scan_lhrh_id_nonmes 
    ON public.cellmes_app_pack_scan (lhrh_id_nonmes);

CREATE INDEX IF NOT EXISTS idx_pack_scan_created_date 
    ON public.cellmes_app_pack_scan (created_date);

-- Station Inspection Compound Subquery Resolvers (pack_id + descending id)
CREATE INDEX IF NOT EXISTS idx_leaktest_pack_id 
    ON public.cellmes_app_leaktest (pack_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_pre_eol_pack_id 
    ON public.cellmes_app_pre_eol (pack_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_eol_pack_id 
    ON public.cellmes_app_eol (pack_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_pdi_station_pack_id 
    ON public.cellmes_pdi_station (pack_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_nc_clearance_pack_id 
    ON public.cellmes_app_nc_clearance (pack_id);

COMMIT;
